use std::sync::Mutex;
use crate::calendar::models::{CalendarSettings, CalendarTask, ProjectItem, TagItem};

pub struct CalendarStore {
    pub tasks: Vec<CalendarTask>,
    pub projects: Vec<ProjectItem>,
    pub tags: Vec<TagItem>,
    pub settings: CalendarSettings,
}

pub struct CalendarState(pub Mutex<CalendarStore>);

impl CalendarState {
    pub fn new_with_sample_data() -> Self {
        let projects = vec![
            ProjectItem {
                id: "proj_1".to_string(),
                name: "[SAMPLE] Project Alpha".to_string(),
                client_name: Some("[SAMPLE] Client B".to_string()),
                color: "#f59e0b".to_string(),
                is_billable: true,
            },
            ProjectItem {
                id: "proj_2".to_string(),
                name: "[SAMPLE] Project Beta".to_string(),
                client_name: Some("[SAMPLE] Client A".to_string()),
                color: "#ef4444".to_string(),
                is_billable: true,
            },
            ProjectItem {
                id: "proj_3".to_string(),
                name: "[SAMPLE] Project Gamma".to_string(),
                client_name: Some("[SAMPLE] Client A".to_string()),
                color: "#8b5cf6".to_string(),
                is_billable: false,
            },
            ProjectItem {
                id: "proj_4".to_string(),
                name: "Clockify Desktop App".to_string(),
                client_name: Some("Internal".to_string()),
                color: "#03a9f4".to_string(),
                is_billable: true,
            },
            ProjectItem {
                id: "proj_5".to_string(),
                name: "Design System & UI".to_string(),
                client_name: Some("Gopalan College".to_string()),
                color: "#10b981".to_string(),
                is_billable: true,
            },
        ];

        let tags = vec![
            TagItem { id: "tag_1".to_string(), name: "Frontend".to_string() },
            TagItem { id: "tag_2".to_string(), name: "Backend".to_string() },
            TagItem { id: "tag_3".to_string(), name: "Meeting".to_string() },
            TagItem { id: "tag_4".to_string(), name: "Design".to_string() },
            TagItem { id: "tag_5".to_string(), name: "Code Review".to_string() },
            TagItem { id: "tag_6".to_string(), name: "Testing".to_string() },
        ];

        let settings = CalendarSettings {
            week_start: "monday".to_string(),
            time_format: "24h".to_string(),
            default_duration: 30,
            show_weekends: true,
            working_hours_start: "09:00".to_string(),
            working_hours_end: "18:00".to_string(),
        };

        let tasks = vec![
            CalendarTask {
                id: "ct_1".to_string(),
                title: "Daily Standup & Sprint Sync".to_string(),
                project_id: Some("proj_4".to_string()),
                project_name: "Clockify Desktop App".to_string(),
                project_color: "#03a9f4".to_string(),
                client_name: Some("Internal".to_string()),
                date: "2026-08-31".to_string(),
                start_time: "09:30".to_string(),
                end_time: "10:30".to_string(),
                duration_minutes: 60,
                is_billable: true,
                tags: vec!["Meeting".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m4".to_string(),
                status: "completed".to_string(),
                created_at: "2026-08-31T09:30:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_2".to_string(),
                title: "Calendar Task Module Architecture".to_string(),
                project_id: Some("proj_4".to_string()),
                project_name: "Clockify Desktop App".to_string(),
                project_color: "#03a9f4".to_string(),
                client_name: Some("Internal".to_string()),
                date: "2026-08-31".to_string(),
                start_time: "11:00".to_string(),
                end_time: "13:00".to_string(),
                duration_minutes: 120,
                is_billable: true,
                tags: vec!["Frontend".to_string(), "Backend".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m4".to_string(),
                status: "completed".to_string(),
                created_at: "2026-08-31T11:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_3".to_string(),
                title: "Sprint Milestone: Delivery Phase 1".to_string(),
                project_id: Some("proj_5".to_string()),
                project_name: "Design System & UI".to_string(),
                project_color: "#10b981".to_string(),
                client_name: Some("Gopalan College".to_string()),
                date: "2026-08-31".to_string(),
                start_time: "00:00".to_string(),
                end_time: "23:59".to_string(),
                duration_minutes: 0,
                is_billable: false,
                tags: vec!["Design".to_string()],
                entry_type: "planned".to_string(),
                member_id: "m4".to_string(),
                status: "planned".to_string(),
                created_at: "2026-08-31T00:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_4".to_string(),
                title: "UI Component Library Review".to_string(),
                project_id: Some("proj_5".to_string()),
                project_name: "Design System & UI".to_string(),
                project_color: "#10b981".to_string(),
                client_name: Some("Gopalan College".to_string()),
                date: "2026-09-01".to_string(),
                start_time: "10:00".to_string(),
                end_time: "12:00".to_string(),
                duration_minutes: 120,
                is_billable: true,
                tags: vec!["Design".to_string(), "Frontend".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m4".to_string(),
                status: "completed".to_string(),
                created_at: "2026-09-01T10:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_5".to_string(),
                title: "Client Feature Roadmap Presentation".to_string(),
                project_id: Some("proj_1".to_string()),
                project_name: "[SAMPLE] Project Alpha".to_string(),
                project_color: "#f59e0b".to_string(),
                client_name: Some("[SAMPLE] Client B".to_string()),
                date: "2026-09-01".to_string(),
                start_time: "14:00".to_string(),
                end_time: "15:30".to_string(),
                duration_minutes: 90,
                is_billable: true,
                tags: vec!["Meeting".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m5".to_string(),
                status: "completed".to_string(),
                created_at: "2026-09-01T14:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_6".to_string(),
                title: "Backend API Performance Profiling".to_string(),
                project_id: Some("proj_2".to_string()),
                project_name: "[SAMPLE] Project Beta".to_string(),
                project_color: "#ef4444".to_string(),
                client_name: Some("[SAMPLE] Client A".to_string()),
                date: "2026-09-02".to_string(),
                start_time: "11:00".to_string(),
                end_time: "13:30".to_string(),
                duration_minutes: 150,
                is_billable: true,
                tags: vec!["Backend".to_string(), "Testing".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m4".to_string(),
                status: "completed".to_string(),
                created_at: "2026-09-02T11:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_7".to_string(),
                title: "Planned: Refactor Time Tracking Hook".to_string(),
                project_id: Some("proj_4".to_string()),
                project_name: "Clockify Desktop App".to_string(),
                project_color: "#03a9f4".to_string(),
                client_name: Some("Internal".to_string()),
                date: "2026-09-02".to_string(),
                start_time: "00:00".to_string(),
                end_time: "23:59".to_string(),
                duration_minutes: 0,
                is_billable: false,
                tags: vec!["Frontend".to_string()],
                entry_type: "planned".to_string(),
                member_id: "m4".to_string(),
                status: "planned".to_string(),
                created_at: "2026-09-02T00:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_8".to_string(),
                title: "Tauri IPC Command Optimization".to_string(),
                project_id: Some("proj_4".to_string()),
                project_name: "Clockify Desktop App".to_string(),
                project_color: "#03a9f4".to_string(),
                client_name: Some("Internal".to_string()),
                date: "2026-09-03".to_string(),
                start_time: "14:00".to_string(),
                end_time: "16:00".to_string(),
                duration_minutes: 120,
                is_billable: true,
                tags: vec!["Backend".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m4".to_string(),
                status: "completed".to_string(),
                created_at: "2026-09-03T14:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_9".to_string(),
                title: "Interactive Calendar View Implementation".to_string(),
                project_id: Some("proj_4".to_string()),
                project_name: "Clockify Desktop App".to_string(),
                project_color: "#03a9f4".to_string(),
                client_name: Some("Internal".to_string()),
                date: "2026-09-04".to_string(),
                start_time: "09:00".to_string(),
                end_time: "12:00".to_string(),
                duration_minutes: 180,
                is_billable: true,
                tags: vec!["Frontend".to_string()],
                entry_type: "entry".to_string(),
                member_id: "m4".to_string(),
                status: "in_progress".to_string(),
                created_at: "2026-09-04T09:00:00Z".to_string(),
                updated_at: None,
            },
            CalendarTask {
                id: "ct_10".to_string(),
                title: "Weekly Sprint Retrospective".to_string(),
                project_id: Some("proj_4".to_string()),
                project_name: "Clockify Desktop App".to_string(),
                project_color: "#03a9f4".to_string(),
                client_name: Some("Internal".to_string()),
                date: "2026-09-04".to_string(),
                start_time: "16:00".to_string(),
                end_time: "17:00".to_string(),
                duration_minutes: 60,
                is_billable: true,
                tags: vec!["Meeting".to_string()],
                entry_type: "planned".to_string(),
                member_id: "m4".to_string(),
                status: "planned".to_string(),
                created_at: "2026-09-04T16:00:00Z".to_string(),
                updated_at: None,
            },
        ];

        CalendarState(Mutex::new(CalendarStore {
            tasks,
            projects,
            tags,
            settings,
        }))
    }
}
