use std::sync::Mutex;
use crate::activity::models::{
    ActivityRecord, ActivitySettings, GeofenceZone, LocationBreadcrumb, MemberLocation,
    ScreenshotItem,
};

pub struct ActivityLocationStore {
    pub activity_records: Vec<ActivityRecord>,
    pub screenshots: Vec<ScreenshotItem>,
    pub member_locations: Vec<MemberLocation>,
    pub geofences: Vec<GeofenceZone>,
    pub settings: ActivitySettings,
}

pub struct ActivityLocationState(pub Mutex<ActivityLocationStore>);

impl ActivityLocationState {
    pub fn new_with_sample_data() -> Self {
        let activity_records = vec![
            ActivityRecord {
                id: "act-1".to_string(),
                member_id: "likith-dt".to_string(),
                member_name: "Likith D T (You)".to_string(),
                avatar: "LD".to_string(),
                avatar_color: "#0288d1".to_string(),
                task: "Clockify Desktop Development".to_string(),
                project: "Project Alpha".to_string(),
                project_color: "#03a9f4".to_string(),
                activity_percent: 98,
                pulse_text: "98% active pulse".to_string(),
                active_window: "VS Code Studio / Terminal".to_string(),
                score: "99% High".to_string(),
                score_color: "text-[#10b981]".to_string(),
                status: "TRACKING".to_string(),
                status_color: "bg-[#ecfdf5] text-[#047857]".to_string(),
                recorded_at: "2026-09-04T10:50:00Z".to_string(),
            },
            ActivityRecord {
                id: "act-2".to_string(),
                member_id: "bindhu-shree".to_string(),
                member_name: "Bindhu shree".to_string(),
                avatar: "BS".to_string(),
                avatar_color: "#00897b".to_string(),
                task: "UI Design Refactoring".to_string(),
                project: "Project Alpha".to_string(),
                project_color: "#03a9f4".to_string(),
                activity_percent: 94,
                pulse_text: "94% active pulse".to_string(),
                active_window: "Figma / Chrome IDE".to_string(),
                score: "96% High".to_string(),
                score_color: "text-[#10b981]".to_string(),
                status: "TRACKING".to_string(),
                status_color: "bg-[#ecfdf5] text-[#047857]".to_string(),
                recorded_at: "2026-09-04T10:50:00Z".to_string(),
            },
            ActivityRecord {
                id: "act-3".to_string(),
                member_id: "priya".to_string(),
                member_name: "Priya Sharma".to_string(),
                avatar: "PS".to_string(),
                avatar_color: "#9333ea".to_string(),
                task: "Database Migration Scripts".to_string(),
                project: "Backend Core".to_string(),
                project_color: "#9333ea".to_string(),
                activity_percent: 86,
                pulse_text: "86% active pulse".to_string(),
                active_window: "VS Code (PostgreSQL)".to_string(),
                score: "88% Optimal".to_string(),
                score_color: "text-[#0288d1]".to_string(),
                status: "TRACKING".to_string(),
                status_color: "bg-[#ecfdf5] text-[#047857]".to_string(),
                recorded_at: "2026-09-04T10:45:00Z".to_string(),
            },
            ActivityRecord {
                id: "act-4".to_string(),
                member_id: "amy-smith".to_string(),
                member_name: "[SAMPLE] Amy Smith".to_string(),
                avatar: "AS".to_string(),
                avatar_color: "#f59e0b".to_string(),
                task: "Client Report Analysis".to_string(),
                project: "Audit Q3".to_string(),
                project_color: "#f59e0b".to_string(),
                activity_percent: 78,
                pulse_text: "78% active pulse".to_string(),
                active_window: "Microsoft Excel".to_string(),
                score: "82% Normal".to_string(),
                score_color: "text-[#0288d1]".to_string(),
                status: "TRACKING".to_string(),
                status_color: "bg-[#ecfdf5] text-[#047857]".to_string(),
                recorded_at: "2026-09-04T10:42:00Z".to_string(),
            },
            ActivityRecord {
                id: "act-5".to_string(),
                member_id: "james-anderson".to_string(),
                member_name: "[SAMPLE] James Anderson".to_string(),
                avatar: "JA".to_string(),
                avatar_color: "#0288d1".to_string(),
                task: "Docker Cluster Setup".to_string(),
                project: "Infrastructure".to_string(),
                project_color: "#64748b".to_string(),
                activity_percent: 91,
                pulse_text: "91% active pulse".to_string(),
                active_window: "Windows Terminal / SSH".to_string(),
                score: "93% High".to_string(),
                score_color: "text-[#10b981]".to_string(),
                status: "TRACKING".to_string(),
                status_color: "bg-[#ecfdf5] text-[#047857]".to_string(),
                recorded_at: "2026-09-04T10:15:00Z".to_string(),
            },
            ActivityRecord {
                id: "act-6".to_string(),
                member_id: "lara-peterson".to_string(),
                member_name: "[SAMPLE] Lara Peterson".to_string(),
                avatar: "LP".to_string(),
                avatar_color: "#ec4899".to_string(),
                task: "Brand Guidelines v2".to_string(),
                project: "Marketing".to_string(),
                project_color: "#ec4899".to_string(),
                activity_percent: 32,
                pulse_text: "32% idle flagged".to_string(),
                active_window: "Slack #design".to_string(),
                score: "45% Low".to_string(),
                score_color: "text-[#f59e0b]".to_string(),
                status: "IDLE".to_string(),
                status_color: "bg-[#fffbeb] text-[#b45309]".to_string(),
                recorded_at: "2026-09-04T10:00:00Z".to_string(),
            },
        ];

        let screenshots = vec![
            ScreenshotItem {
                id: "sc-1".to_string(),
                member_id: "likith-dt".to_string(),
                member_name: "Likith D T (You)".to_string(),
                member_avatar: Some("LD".to_string()),
                timestamp: "2026-08-31T10:40:00Z".to_string(),
                time_formatted: "10:40 AM".to_string(),
                project: "Project Alpha".to_string(),
                project_color: "#03a9f4".to_string(),
                activity_percent: 98,
                app_name: "Figma Desktop App".to_string(),
                window_title: "Workspace UI Master v2.4 - Canvas 1".to_string(),
                code_snippet: None,
                screenshot_type: "figma".to_string(),
            },
            ScreenshotItem {
                id: "sc-2".to_string(),
                member_id: "likith-dt".to_string(),
                member_name: "Likith D T (You)".to_string(),
                member_avatar: Some("LD".to_string()),
                timestamp: "2026-08-31T10:30:00Z".to_string(),
                time_formatted: "10:30 AM".to_string(),
                project: "Frontend Dev".to_string(),
                project_color: "#10b981".to_string(),
                activity_percent: 92,
                app_name: "VS Code Studio".to_string(),
                window_title: "src/components/tracker/TrackerBar.tsx".to_string(),
                code_snippet: Some("const timer = new Stopwatch();\nstartLiveTracker();".to_string()),
                screenshot_type: "code".to_string(),
            },
            ScreenshotItem {
                id: "sc-3".to_string(),
                member_id: "amy-smith".to_string(),
                member_name: "[SAMPLE] Amy Smith".to_string(),
                member_avatar: Some("AS".to_string()),
                timestamp: "2026-08-31T10:20:00Z".to_string(),
                time_formatted: "10:20 AM".to_string(),
                project: "Clockify Web".to_string(),
                project_color: "#ec4899".to_string(),
                activity_percent: 87,
                app_name: "Google Chrome".to_string(),
                window_title: "Activity - Screenshots & GPS Audits".to_string(),
                code_snippet: None,
                screenshot_type: "browser".to_string(),
            },
            ScreenshotItem {
                id: "sc-4".to_string(),
                member_id: "james-anderson".to_string(),
                member_name: "[SAMPLE] James Anderson".to_string(),
                member_avatar: Some("JA".to_string()),
                timestamp: "2026-08-31T10:10:00Z".to_string(),
                time_formatted: "10:10 AM".to_string(),
                project: "DevOps Core".to_string(),
                project_color: "#8b5cf6".to_string(),
                activity_percent: 95,
                app_name: "Terminal / Bash".to_string(),
                window_title: "cargo tauri dev --release".to_string(),
                code_snippet: None,
                screenshot_type: "terminal".to_string(),
            },
            ScreenshotItem {
                id: "sc-5".to_string(),
                member_id: "lara-peterson".to_string(),
                member_name: "[SAMPLE] Lara Peterson".to_string(),
                member_avatar: Some("LP".to_string()),
                timestamp: "2026-08-31T10:00:00Z".to_string(),
                time_formatted: "10:00 AM".to_string(),
                project: "Client Sync".to_string(),
                project_color: "#f59e0b".to_string(),
                activity_percent: 78,
                app_name: "Slack".to_string(),
                window_title: "#sprint-planning · Team Channel".to_string(),
                code_snippet: None,
                screenshot_type: "slack".to_string(),
            },
        ];

        let member_locations = vec![
            MemberLocation {
                id: "likith-dt".to_string(),
                name: "Likith D T (You)".to_string(),
                role: "Workspace Owner & Lead Engineer".to_string(),
                avatar: "LD".to_string(),
                avatar_color: "#0288d1".to_string(),
                is_current_user: Some(true),
                last_seen: "Just now".to_string(),
                status: "Inside Geofence".to_string(),
                status_color: "#10b981".to_string(),
                location_name: "Gopalan College of Engineering and Management, Hoodi, Whitefield, Bengaluru".to_string(),
                lat: 12.9904,
                lng: 77.7126,
                speed: "0 km/h".to_string(),
                battery: 100,
                breadcrumbs: vec![
                    LocationBreadcrumb { lat: 12.9890, lng: 77.7110, time: "09:00 AM".to_string() },
                    LocationBreadcrumb { lat: 12.9904, lng: 77.7126, time: "10:50 AM".to_string() },
                ],
            },
            MemberLocation {
                id: "bindhu-shree".to_string(),
                name: "Bindhu shree".to_string(),
                role: "Backend Developer".to_string(),
                avatar: "BS".to_string(),
                avatar_color: "#00897b".to_string(),
                is_current_user: Some(false),
                last_seen: "-".to_string(),
                status: "Inside Geofence".to_string(),
                status_color: "#10b981".to_string(),
                location_name: "Gopalan College Campus, Whitefield, Bengaluru".to_string(),
                lat: 12.9850,
                lng: 77.7280,
                speed: "0 km/h".to_string(),
                battery: 97,
                breadcrumbs: vec![
                    LocationBreadcrumb { lat: 12.9840, lng: 77.7265, time: "09:00 AM".to_string() },
                    LocationBreadcrumb { lat: 12.9850, lng: 77.7280, time: "10:50 AM".to_string() },
                ],
            },
            MemberLocation {
                id: "amy-smith".to_string(),
                name: "[SAMPLE] Amy Smith".to_string(),
                role: "Frontend Developer".to_string(),
                avatar: "AS".to_string(),
                avatar_color: "#f59e0b".to_string(),
                is_current_user: Some(false),
                last_seen: "-".to_string(),
                status: "Inside Geofence".to_string(),
                status_color: "#10b981".to_string(),
                location_name: "Whitefield Site 2, Bengaluru".to_string(),
                lat: 12.9865,
                lng: 77.7295,
                speed: "0 km/h".to_string(),
                battery: 92,
                breadcrumbs: vec![
                    LocationBreadcrumb { lat: 12.9825, lng: 77.7240, time: "09:00 AM".to_string() },
                    LocationBreadcrumb { lat: 12.9865, lng: 77.7295, time: "10:30 AM".to_string() },
                ],
            },
            MemberLocation {
                id: "james-anderson".to_string(),
                name: "[SAMPLE] James Anderson".to_string(),
                role: "DevOps Engineer".to_string(),
                avatar: "JA".to_string(),
                avatar_color: "#0288d1".to_string(),
                is_current_user: Some(false),
                last_seen: "-".to_string(),
                status: "Inside Geofence".to_string(),
                status_color: "#10b981".to_string(),
                location_name: "Gopalan Tech Park, Bengaluru".to_string(),
                lat: 12.9835,
                lng: 77.7255,
                speed: "4 km/h".to_string(),
                battery: 88,
                breadcrumbs: vec![
                    LocationBreadcrumb { lat: 12.9810, lng: 77.7220, time: "08:30 AM".to_string() },
                    LocationBreadcrumb { lat: 12.9835, lng: 77.7255, time: "10:15 AM".to_string() },
                ],
            },
            MemberLocation {
                id: "lara-peterson".to_string(),
                name: "[SAMPLE] Lara Peterson".to_string(),
                role: "Product Designer".to_string(),
                avatar: "LP".to_string(),
                avatar_color: "#ec4899".to_string(),
                is_current_user: Some(false),
                last_seen: "-".to_string(),
                status: "Outside Zone".to_string(),
                status_color: "#f59e0b".to_string(),
                location_name: "Indiranagar 100ft Rd, Bengaluru".to_string(),
                lat: 12.9784,
                lng: 77.6408,
                speed: "18 km/h".to_string(),
                battery: 74,
                breadcrumbs: vec![
                    LocationBreadcrumb { lat: 12.9800, lng: 77.6450, time: "09:15 AM".to_string() },
                    LocationBreadcrumb { lat: 12.9784, lng: 77.6408, time: "10:45 AM".to_string() },
                ],
            },
            MemberLocation {
                id: "mike-johnson".to_string(),
                name: "[SAMPLE] Mike Johnson".to_string(),
                role: "Quality Assurance".to_string(),
                avatar: "MJ".to_string(),
                avatar_color: "#8b5cf6".to_string(),
                is_current_user: Some(false),
                last_seen: "-".to_string(),
                status: "Inside Geofence".to_string(),
                status_color: "#10b981".to_string(),
                location_name: "Electronic City Phase 1, Bengaluru".to_string(),
                lat: 12.8452,
                lng: 77.6602,
                speed: "0 km/h".to_string(),
                battery: 65,
                breadcrumbs: vec![
                    LocationBreadcrumb { lat: 12.8410, lng: 77.6580, time: "08:45 AM".to_string() },
                    LocationBreadcrumb { lat: 12.8452, lng: 77.6602, time: "10:20 AM".to_string() },
                ],
            },
        ];

        let geofences = vec![
            GeofenceZone {
                id: "geo-1".to_string(),
                name: "Gopalan College Campus".to_string(),
                address: "Hoodi, Whitefield, Bengaluru, Karnataka 560048".to_string(),
                lat: 12.9904,
                lng: 77.7126,
                radius_meters: 450.0,
                color: "#10b981".to_string(),
            },
            GeofenceZone {
                id: "geo-2".to_string(),
                name: "Whitefield Tech Hub Zone".to_string(),
                address: "ITPL Main Road, Whitefield, Bengaluru".to_string(),
                lat: 12.9850,
                lng: 77.7280,
                radius_meters: 750.0,
                color: "#0288d1".to_string(),
            },
            GeofenceZone {
                id: "geo-3".to_string(),
                name: "Electronic City Headquarters".to_string(),
                address: "Electronic City Phase 1, Bengaluru".to_string(),
                lat: 12.8452,
                lng: 77.6602,
                radius_meters: 1000.0,
                color: "#8b5cf6".to_string(),
            },
        ];

        let settings = ActivitySettings {
            is_monitoring_active: true,
            is_screenshots_active: true,
            is_gps_active: true,
            blur_privacy: false,
            screenshot_frequency_minutes: 5,
        };

        ActivityLocationState(Mutex::new(ActivityLocationStore {
            activity_records,
            screenshots,
            member_locations,
            geofences,
            settings,
        }))
    }
}
